### ISSUE TITLE
Install in 3.9

### ISSUE THREAD

**Issue by hmgp** [vadimonus/moodle-quizaccess_onesession#6] opened 2020-09-14 10:31 UTC
Hello, I'm trying to install in 3.9 but it does no install. Stays in a page has it was installing and does nothing. No errors appear on moodle logs, no errors appear even if I have the website in developer mode. Does this install in 3.9? Are there plans to make it install in 3.9? Thank you!

**Comment by vadimonus** [comment] 2020-09-14 10:44
I did not tested this plugin on 3.9, but stats reports that there are more than 50 sites with 3.9 where this plugin is installed. Try to find some logs (php or webserver) to identify error. Try install at local, if error was on server. Check owner and rights for plugin folder.
I will not have time to manually test this plugin in next two monthes

**Comment by hmgp** [comment] 2020-09-14 12:12
Hi! Thank you for your quick reply. 
Can you tell me where I can see those stats reports? Or can you tell me the type of database used in those 3.9 installations?

**Comment by hmgp** [comment] 2020-09-14 12:22
I know you can't see this problem, just for future memory and if anyone else has this, the plugin, when upgrading or installing, I tried both, stays in this page and does nothing:

![Screenshot from 2020-09-14 13-19-54](https://user-images.githubusercontent.com/52750094/93085268-3ea45480-f68d-11ea-970d-24ac8c4a65d1.png)

**Comment by vadimonus** [comment] 2021-01-03 12:44
Closed as cannot reproduce

**Closed as completed by vadimonus** 2021-01-03 12:44 UTC
