### ISSUE TITLE
fatal error once the student is prevent from resuming quiz

### ISSUE THREAD

**Issue by hribeir0** [vadimonus/moodle-quizaccess_onesession#2] opened 2019-04-09 11:11 UTC
Hi Vadim.
Thank you for great work. We've installed it in moodle 3.5, however we get a fatal error once the student is prevent (rightly) from accessing the quiz again instead of another more friendly error message. Perhaps print_error() shouldn't be used?

**Comment by vadimonus** [comment] 2020-06-06 21:17
Currently it's standart practice in moodle to use print_error when access is prevented, e.g. if it's no rights.
Please provide screenshot, to check if it's not the same that was originally

**Comment by vadimonus** [comment] 2021-01-03 12:45
Closed as not a bug

**Closed as completed by vadimonus** 2021-01-03 12:45 UTC
